name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
#          - macos-latest
          - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install -y ghostscript gnupg2 imagemagick zbar-tools && sudo pip install -r requirements.txt
      - name: Run tests
        run: make test
